services:
  redis: 
    image: redis:alpine
  
  app:
    build: .
    container_name: python-server
    command: >
            sh -c   "pip install debugpy -t /tmp && 
                    python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/main.py"
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis

  